#!/usr/bin/env python3
"""
build_interface_transport.py — Interface Geometric Transport Analysis
======================================================================
Treats each patient's tumor–immune interface as a metric measure space
(I, d, μ) and computes pre→post therapy transport distances.

Three transport metrics per patient:
──────────────────────────────────────────────────────────────────────
1. WASSERSTEIN-2 DISTANCE  W₂(μ_pre, μ_post)
   Measures how much coexact "mass" was geometrically redistributed.
   Large W₂: active spatial reorganization of non-gradient structure.
   Small W₂: mass stayed in place (preservation or uniform collapse).

2. TRAJECTORY IN FEATURE SPACE  ΔX = X_post - X_pre
   X = (LCC, Gini, P95_norm, CoexactFrac, SpecEntropy)
   Tests whether R and NR therapy trajectories are directionally coherent
   — the Lipschitz question operationalised.

3. PERSISTENT TOPOLOGY  (via gudhi, Vietoris-Rips on interface nodes)
   H0: birth/death of connected coexact density clusters
   H1: persistent topological loops (circulation topology)
   Computes:
     - max H0 persistence (most robust hotspot cluster lifetime)
     - total H1 persistence (circulation topology, sum of loop lifetimes)
     - n_H1_persistent: number of loops surviving > persistence_threshold

Mathematical object
───────────────────
For each quality-filtered sample:
  coords_I = spatial coordinates of interface nodes
  mu_I     = coexact density c_i at interface nodes, normalised to sum=1

W₂ is computed via entropic regularised optimal transport (POT library).
Persistent homology via gudhi.RipsComplex on the spatial distance matrix.

Inputs
──────
results_hcc_coexact_hotspots.csv — for feature space vectors
data/hepatocellular_carcinoma/hcc_*_coexact.h5ad — for spatial data
  (generated by build_coexact_spatial.py; must be run first)

Outputs
───────
results_hcc_transport.csv          per-patient W2 and trajectory metrics
results_hcc_persistence.csv        per-sample persistence diagram summary
fig_hcc_trajectory_space.png       pre→post arrows in (LCC, CoexactFrac) space
fig_hcc_wasserstein_comparison.png W₂ by response group
"""

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
import scanpy as sc
import ot
import gudhi
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from scipy.stats import mannwhitneyu

# ── Patient metadata ───────────────────────────────────────────────────────
PATIENT_MAP = {
    'cytassist_70': (85557, 'Responder'),    'cytassist_71': (85558, 'Responder'),
    'cytassist_72': (85559, 'Non_Responder'),'cytassist_73': (85560, 'Non_Responder'),
    'cytassist_74': (85561, 'Non_Responder'),'cytassist_76': (85563, 'Responder'),
    'cytassist_79': (85565, 'Non_Responder'),'cytassist_83': (85566, 'Responder'),
    'cytassist_84': (85567, 'Responder'),    'cytassist_85': (85568, 'Non_Responder'),
    'cytassist_86': (85569, 'Non_Responder'),
}
COLOURS = {'Responder': '#d62728', 'Non_Responder': '#1f77b4'}


def _make_rips(coords: np.ndarray, max_edge_length: float):
    """
    Compatibility wrapper for gudhi.RipsComplex.
    Handles two incompatible API versions:
      Keyword-only  (most builds):  RipsComplex(points=..., max_edge_length=...)
      Positional-only (some builds, e.g. Python 3.14):
                                    RipsComplex(pts, max_edge_length, False)
    """
    import inspect
    pts = np.ascontiguousarray(coords, dtype=np.float64)
    sig = inspect.signature(gudhi.RipsComplex.__init__)
    if 'points' in sig.parameters:
        return gudhi.RipsComplex(points=pts, max_edge_length=max_edge_length)
    # Positional-only: third arg is sparse_flag (False = full Rips)
    return gudhi.RipsComplex(pts, max_edge_length, False)
EXCLUDE = {'small_interface', 'low_tumor_signal', 'subgraph_too_small',
           'too_few_spots', 'low_tumor', 'skip'}


# ══════════════════════════════════════════════════════════════════════════════
# WASSERSTEIN DISTANCE
# ══════════════════════════════════════════════════════════════════════════════

def wasserstein2_interface(coords_pre: np.ndarray, mu_pre: np.ndarray,
                           coords_post: np.ndarray, mu_post: np.ndarray,
                           reg: float = 0.1) -> float:
    """
    Entropic-regularised W₂ between two interface coexact density measures.

    coords: (n, 2) spatial coordinates of interface nodes
    mu:     (n,)  coexact density, will be normalised to sum=1

    Uses POT (Python Optimal Transport) entropic OT for efficiency.
    reg: entropic regularisation (higher = faster, less accurate).
    """
    # Force contiguous float64 arrays (POT requires proper numpy arrays)
    coords_pre  = np.ascontiguousarray(coords_pre,  dtype=np.float64)
    coords_post = np.ascontiguousarray(coords_post, dtype=np.float64)

    # Normalise to probability measures
    a = np.abs(np.asarray(mu_pre,  dtype=np.float64))
    b = np.abs(np.asarray(mu_post, dtype=np.float64))
    if a.sum() < 1e-12 or b.sum() < 1e-12:
        return np.nan
    a /= a.sum(); b /= b.sum()

    # Squared Euclidean cost matrix (W₂ uses squared distances)
    M = ot.dist(coords_pre, coords_post, metric='sqeuclidean')
    # Normalise by median to make scale-invariant
    med = np.median(M[M > 0]) if (M > 0).any() else 1.
    M  /= med

    # Entropic OT (Sinkhorn)
    try:
        result = ot.sinkhorn2(a, b, M, reg=reg)
        W2 = float(result) if np.isscalar(result) else float(result[0])
    except Exception:
        W2 = np.nan
    return W2


# ══════════════════════════════════════════════════════════════════════════════
# PERSISTENT HOMOLOGY
# ══════════════════════════════════════════════════════════════════════════════

def persistent_topology(coords: np.ndarray, density: np.ndarray,
                        max_edge_length: float | None = None,
                        persistence_threshold: float = 0.05
                        ) -> dict:
    """
    Vietoris-Rips persistent homology on interface node positions,
    weighted by coexact density.

    The filtration value for an edge is its spatial length.
    The 'birth' of a H0 class corresponds to a spatial cluster forming;
    the 'death' corresponds to that cluster merging with another.

    Returns summary statistics of H0 and H1 persistence diagrams.
    """
    n = len(coords)
    if n < 4:
        return dict(max_h0_persistence=np.nan, sum_h0_persistence=np.nan,
                    n_h0_persistent=0, max_h1_persistence=np.nan,
                    sum_h1_persistence=np.nan, n_h1_persistent=0)

    # Auto-set max edge length as 2× median nearest-neighbour distance
    if max_edge_length is None:
        from sklearn.neighbors import NearestNeighbors
        nbrs = NearestNeighbors(n_neighbors=2).fit(coords)
        dists, _ = nbrs.kneighbors(coords)
        max_edge_length = float(np.median(dists[:, 1]) * 6)

    rips = _make_rips(coords, max_edge_length)
    st   = rips.create_simplex_tree(max_dimension=2)
    st.compute_persistence()
    diag = st.persistence()

    h0 = [(birth, death) for (dim, (birth, death)) in diag
          if dim == 0 and np.isfinite(death)]
    h1 = [(birth, death) for (dim, (birth, death)) in diag
          if dim == 1 and np.isfinite(death)]

    h0_pers = [d - b for b, d in h0]
    h1_pers = [d - b for b, d in h1]

    return dict(
        max_h0_persistence   = float(max(h0_pers)) if h0_pers else 0.,
        sum_h0_persistence   = float(sum(h0_pers)) if h0_pers else 0.,
        n_h0_persistent      = int(sum(1 for p in h0_pers
                                       if p > persistence_threshold)),
        max_h1_persistence   = float(max(h1_pers)) if h1_pers else 0.,
        sum_h1_persistence   = float(sum(h1_pers)) if h1_pers else 0.,
        n_h1_persistent      = int(sum(1 for p in h1_pers
                                       if p > persistence_threshold)),
    )


# ══════════════════════════════════════════════════════════════════════════════
# FEATURE SPACE TRAJECTORY
# ══════════════════════════════════════════════════════════════════════════════

def feature_vector(row: pd.Series, p95_scale: float = 1.) -> np.ndarray:
    """
    X = (LCC, Gini, P95_scaled, CoexactFrac, SpecEntropy)
    Returns NaN vector if any metric is missing.
    """
    try:
        return np.array([
            float(row.get('largest_component_fraction', np.nan)),
            float(row.get('hotspot_gini',               np.nan)),
            float(row.get('hotspot_p95',                np.nan)) / p95_scale,
            float(row.get('coexact_fraction',           np.nan)),
            float(row.get('spec_spectral_entropy',      np.nan)),
        ])
    except Exception:
        return np.full(5, np.nan)


# ══════════════════════════════════════════════════════════════════════════════
# FIGURES
# ══════════════════════════════════════════════════════════════════════════════

def plot_trajectory(transport_df: pd.DataFrame, hotspot_df: pd.DataFrame,
                    outpath: Path) -> None:
    """
    Pre→post arrows in (LCC, CoexactFrac) space and (Gini, LCC) space.
    """
    fig, axes = plt.subplots(1, 2, figsize=(13, 5))
    fig.suptitle('Interface geometry trajectories: pre→post therapy\n'
                 '(arrows show direction of change per patient)',
                 fontsize=11)

    ok = hotspot_df[~hotspot_df['status'].isin(EXCLUDE)].copy()

    for ax, (xcol, ycol, xlabel, ylabel) in zip(axes, [
        ('largest_component_fraction', 'coexact_fraction',
         'LCC fraction', 'Coexact fraction'),
        ('hotspot_gini', 'largest_component_fraction',
         'Gini', 'LCC fraction'),
    ]):
        pre  = ok[ok['timepoint'] == 'pre'].set_index('cytassist_id')
        post = ok[ok['timepoint'] == 'post'].set_index('cytassist_id')

        for cid in pre.index:
            if cid not in post.index: continue
            pr, po = pre.loc[cid], post.loc[cid]
            if xcol not in pr or ycol not in pr: continue
            resp = pr.get('response_group', 'Unknown')
            col  = COLOURS.get(resp, 'grey')
            xp, yp = float(pr[xcol]), float(pr[ycol])
            xo, yo = float(po[xcol]), float(po[ycol])
            if not all(np.isfinite([xp, yp, xo, yo])): continue

            ax.annotate('', xy=(xo, yo), xytext=(xp, yp),
                        arrowprops=dict(arrowstyle='->', color=col, lw=1.5))
            ax.scatter([xp], [yp], color=col, s=60, zorder=3)
            ax.text(xp - 0.01, yp + 0.005,
                    cid.replace('cytassist_', ''),
                    fontsize=7, color=col, ha='right')

        ax.set_xlabel(xlabel, fontsize=10); ax.set_ylabel(ylabel, fontsize=10)
        ax.axhline(0, color='grey', lw=0.5, ls='--')
        ax.axvline(0, color='grey', lw=0.5, ls='--')

    fig.legend(handles=[
        mpatches.Patch(color='#d62728', label='Responder'),
        mpatches.Patch(color='#1f77b4', label='Non-Responder'),
    ], fontsize=9, loc='lower center', ncol=2, bbox_to_anchor=(0.5, -0.04))
    plt.tight_layout()
    plt.savefig(outpath, dpi=180, bbox_inches='tight')
    plt.close()


def plot_wasserstein(transport_df: pd.DataFrame, outpath: Path) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    fig.suptitle('Interface transport geometry: W₂ and trajectory displacement\n'
                 '(quality-filtered pairs only)', fontsize=11)

    rng = np.random.RandomState(42)
    for ax, col, ylabel in [
        (axes[0], 'wasserstein2',
         'W₂ (entropic OT, normalised)\nlarger = more spatial redistribution'),
        (axes[1], 'trajectory_norm',
         '||ΔX|| in feature space\nlarger = more geometric change'),
    ]:
        for xi, (resp, c) in enumerate([
            ('Responder','#d62728'), ('Non_Responder','#1f77b4')
        ]):
            grp = transport_df[transport_df['Response'] == resp][col].dropna()
            if len(grp) == 0: continue
            jx  = xi + rng.uniform(-0.18, 0.18, len(grp))
            ax.scatter(jx, grp.values, color=c, s=80, zorder=3, alpha=0.9)
            ax.plot([xi-.3, xi+.3], [grp.median()]*2, color=c, lw=2.5, zorder=4)
            for i, (_, row) in enumerate(
                transport_df[transport_df['Response']==resp].dropna(subset=[col]).iterrows()
            ):
                ax.text(xi+.22, row[col],
                        row['cytassist_id'].replace('cytassist_',''),
                        fontsize=7, va='center', color=c)

        ax.axhline(0, color='grey', lw=0.5, ls='--')
        ax.set_xticks([0,1])
        ax.set_xticklabels(['Responder','Non-Responder'], fontsize=10)
        ax.set_ylabel(ylabel, fontsize=9)

        r_v  = transport_df[transport_df['Response']=='Responder'][col].dropna()
        nr_v = transport_df[transport_df['Response']=='Non_Responder'][col].dropna()
        if len(r_v) > 0 and len(nr_v) > 0:
            _, p = mannwhitneyu(r_v, nr_v, alternative='two-sided')
            ax.set_title(f'Mann-Whitney p = {p:.3f}', fontsize=9)

    fig.legend(handles=[
        mpatches.Patch(color='#d62728', label='Responder'),
        mpatches.Patch(color='#1f77b4', label='Non-Responder'),
    ], fontsize=9, loc='lower center', ncol=2, bbox_to_anchor=(0.5,-0.04))
    plt.tight_layout()
    plt.savefig(outpath, dpi=180, bbox_inches='tight')
    plt.close()


# ══════════════════════════════════════════════════════════════════════════════
# MAIN
# ══════════════════════════════════════════════════════════════════════════════

def main():
    ap = argparse.ArgumentParser(
        description='Interface geometric transport analysis')
    ap.add_argument('--hotspot-csv',   default='results_hcc_coexact_hotspots.csv')
    ap.add_argument('--hodge-csv',     default='results_hcc_hodge_interface_summary.csv')
    ap.add_argument('--h5ad-dir',      default='data/hepatocellular_carcinoma')
    ap.add_argument('--ot-reg',        type=float, default=0.05,
                    help='Sinkhorn entropic regularisation (default 0.05)')
    ap.add_argument('--persist-thresh',type=float, default=0.05,
                    help='Persistence threshold for H0/H1 counting')
    ap.add_argument('--out-transport', default='results_hcc_transport.csv')
    ap.add_argument('--out-persist',   default='results_hcc_persistence.csv')
    ap.add_argument('--fig-traj',      default='fig_hcc_trajectory_space.png')
    ap.add_argument('--fig-wass',      default='fig_hcc_wasserstein_comparison.png')
    args = ap.parse_args()

    hot  = pd.read_csv(args.hotspot_csv)
    # Load Hodge interface summary for coexact_fraction
    try:
        hodge = pd.read_csv(args.hodge_csv)
        hodge_lookup = hodge.set_index('sample_id')
    except Exception:
        hodge_lookup = pd.DataFrame()

    ok   = hot[~hot['status'].isin(EXCLUDE)].copy()
    ok['cytassist_id'] = ok['sample_id'].str.extract(r'(cytassist_\d+)')
    ok['timepoint']    = ok['sample_id'].str.extract(r'(pre|post)$')

    # Add coexact_fraction from hodge summary if available
    if 'coexact_fraction' not in ok.columns and not hodge_lookup.empty:
        ok['coexact_fraction'] = ok['sample_id'].map(
            hodge_lookup.get('coexact_fraction', pd.Series(dtype=float)))

    # P95 scale for normalisation (cohort 95th percentile)
    p95_scale = float(ok['hotspot_p95'].quantile(0.95)) or 1.

    h5ad_dir  = Path(args.h5ad_dir)
    transport_rows = []
    persist_rows   = []

    print(f"\nProcessing paired patients …")
    for cid, grp in ok.groupby('cytassist_id'):
        pid, resp = PATIENT_MAP.get(cid, (None, None))
        pre_rows  = grp[grp['timepoint'] == 'pre']
        post_rows = grp[grp['timepoint'] == 'post']
        if len(pre_rows) == 0 or len(post_rows) == 0:
            continue

        pre_sid  = pre_rows.iloc[0]['sample_id']
        post_sid = post_rows.iloc[0]['sample_id']
        print(f"\n── {cid}  ({resp}) ──")

        # Load h5ad files
        pre_h5  = h5ad_dir / f'hcc_{pre_sid}_coexact.h5ad'
        post_h5 = h5ad_dir / f'hcc_{post_sid}_coexact.h5ad'
        if not pre_h5.exists() or not post_h5.exists():
            print(f"  SKIP — h5ad missing ({pre_h5.exists()} {post_h5.exists()})")
            continue

        pre_adata  = sc.read_h5ad(pre_h5)
        post_adata = sc.read_h5ad(post_h5)

        # Extract interface nodes and coexact density
        for label, adata in [('pre', pre_adata), ('post', post_adata)]:
            iface_mask   = adata.obs['interface_mask'].values.astype(bool)
            coords_iface = adata.obsm['spatial'][iface_mask]
            density_iface = adata.obs['coexact_density'].values[iface_mask]
            n_iface = int(iface_mask.sum())
            print(f"  {label}: n_interface={n_iface}  "
                  f"density_max={density_iface.max():.2f}")

            if n_iface >= 4 and density_iface.sum() > 1e-8:
                pt = persistent_topology(coords_iface, density_iface,
                                         persistence_threshold=args.persist_thresh)
                persist_rows.append(dict(
                    sample_id=f'hcc_{pre_sid if label=="pre" else post_sid}',
                    cytassist_id=cid, timepoint=label,
                    patient_id=pid, Response=resp,
                    n_interface=n_iface, **pt))
                print(f"    H0 max_pers={pt['max_h0_persistence']:.3f}  "
                      f"H1 max_pers={pt['max_h1_persistence']:.3f}  "
                      f"n_H1_persist={pt['n_h1_persistent']}")

        # Wasserstein distance pre→post
        iface_pre  = pre_adata.obs['interface_mask'].values.astype(bool)
        iface_post = post_adata.obs['interface_mask'].values.astype(bool)
        coords_pre  = np.ascontiguousarray(
            pre_adata.obsm['spatial'][iface_pre],  dtype=np.float64)
        coords_post = np.ascontiguousarray(
            post_adata.obsm['spatial'][iface_post], dtype=np.float64)
        den_pre  = np.asarray(
            pre_adata.obs['coexact_density'].values[iface_pre],  dtype=np.float64)
        den_post = np.asarray(
            post_adata.obs['coexact_density'].values[iface_post], dtype=np.float64)

        w2 = np.nan
        if (len(den_pre) >= 4 and len(den_post) >= 4 and
                den_pre.sum() > 1e-8 and den_post.sum() > 1e-8):
            w2 = wasserstein2_interface(coords_pre, den_pre,
                                        coords_post, den_post,
                                        reg=args.ot_reg)
            print(f"  W₂(pre→post) = {w2:.4f}")

        # Feature space trajectory
        X_pre  = feature_vector(pre_rows.iloc[0],  p95_scale)
        X_post = feature_vector(post_rows.iloc[0], p95_scale)
        delta_X    = X_post - X_pre
        traj_norm  = float(np.linalg.norm(delta_X[np.isfinite(delta_X)]))
        traj_angle = float(np.degrees(np.arctan2(
            delta_X[0] if np.isfinite(delta_X[0]) else 0,   # ΔLCC
            delta_X[3] if np.isfinite(delta_X[3]) else 0,   # ΔCoexactFrac
        )))

        transport_rows.append(dict(
            cytassist_id     = cid,
            patient_id       = pid,
            Response         = resp,
            n_pre            = int(pre_rows.iloc[0]['n_interface']),
            n_post           = int(post_rows.iloc[0]['n_interface']),
            wasserstein2     = w2,
            trajectory_norm  = traj_norm,
            trajectory_angle = traj_angle,
            delta_lcc        = float(delta_X[0]) if np.isfinite(delta_X[0]) else np.nan,
            delta_gini       = float(delta_X[1]) if np.isfinite(delta_X[1]) else np.nan,
            delta_coexact_frac = float(delta_X[3]) if np.isfinite(delta_X[3]) else np.nan,
            delta_spec_entropy = float(delta_X[4]) if np.isfinite(delta_X[4]) else np.nan,
            spatial_score_pre  = float(pre_rows.iloc[0]['hotspot_gini']
                                       * pre_rows.iloc[0]['largest_component_fraction']),
            spatial_score_post = float(post_rows.iloc[0]['hotspot_gini']
                                       * post_rows.iloc[0]['largest_component_fraction']),
        ))

    transport_df = pd.DataFrame(transport_rows)
    persist_df   = pd.DataFrame(persist_rows)

    transport_df.to_csv(args.out_transport, index=False)
    persist_df.to_csv(args.out_persist,    index=False)
    print(f'\nSaved → {args.out_transport}')
    print(f'Saved → {args.out_persist}')

    # ── Figures ───────────────────────────────────────────────────────────
    plot_trajectory(transport_df, hot, Path(args.fig_traj))
    plot_wasserstein(transport_df, Path(args.fig_wass))
    print(f'Saved → {args.fig_traj}')
    print(f'Saved → {args.fig_wass}')

    # ── Statistics ────────────────────────────────────────────────────────
    print('\n' + '='*65)
    print('TRANSPORT METRICS (paired patients)')
    print('='*65)
    print(transport_df[[
        'cytassist_id','Response','n_pre','n_post',
        'wasserstein2','trajectory_norm','delta_lcc','delta_coexact_frac'
    ]].to_string(index=False))

    for col, label in [('wasserstein2','W₂'), ('trajectory_norm','||ΔX||')]:
        r  = transport_df[transport_df['Response']=='Responder'][col].dropna()
        nr = transport_df[transport_df['Response']=='Non_Responder'][col].dropna()
        if len(r) > 0 and len(nr) > 0:
            _, p2 = mannwhitneyu(r, nr, alternative='two-sided')
            print(f'\n  {label}: R median={r.median():.4f}  NR median={nr.median():.4f}  '
                  f'p(two-sided)={p2:.4f}')

    print('\n' + '='*65)
    print('PERSISTENCE SUMMARY')
    print('='*65)
    if not persist_df.empty:
        print(persist_df[[
            'cytassist_id','timepoint','Response','n_interface',
            'max_h0_persistence','max_h1_persistence','n_h1_persistent'
        ]].to_string(index=False))

        for tp in ['pre','post']:
            sub = persist_df[persist_df['timepoint']==tp]
            r   = sub[sub['Response']=='Responder']['max_h1_persistence'].dropna()
            nr  = sub[sub['Response']=='Non_Responder']['max_h1_persistence'].dropna()
            if len(r) > 0 and len(nr) > 0:
                print(f'\n  H1 max persistence ({tp}):  '
                      f'R median={r.median():.3f}  NR median={nr.median():.3f}')


if __name__ == '__main__':
    main()
